// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://woirnkogwwoqizokcmid.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndvaXJua29nd3dvcWl6b2tjbWlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk3MDIzODEsImV4cCI6MjA3NTI3ODM4MX0.7lrQbosHnIvf60bv05jh-DybjWDPEVL97Oq0Lg7WjSo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});