// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iydzttmgzxbucisbqbiw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5ZHp0dG1nenhidWNpc2JxYml3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NjkxODUsImV4cCI6MjA3NDI0NTE4NX0.4iCND6kYdw13Mls9d1ZaWdLGPRJqKpRen1O-ebYvL3s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});